### ISSUE TITLE
large memory consumption

### ISSUE THREAD

**Issue by m-iDev-0792** [palanglois/line-surface-reconstruction#1]
Hi, Palanglois!
Thanks for your great work. I am trying to reconstruct some scenes using your program. I managed to compile your code on my machine and try to reconstruct a scene that contains about 3k lines. I did run `ransac_on_lines` smoothly, but when running `line_based_recons_param` and `line_based_recons`, these two programs consumed large amount of memory and reached my machine memory limit (64GB), and finally killed by Linux. I found that the program consumes about 20GB memory when logs out 'Inserted n primitives out of N', after that, it consumed memory at a very fast speed when performing `Building the intersection tree...`. The memory usage always reached the limit at this step.
Is this caused by my misusage (e.g. inappropriate parameters) ? or this program does need so much memory?
Can you provide some tips to reduce memory usage?
Thanks!
![10611620837994_ pic_hd](https://user-images.githubusercontent.com/24957019/118067415-16fbbc80-b3d3-11eb-959e-4ca203536218.jpg)

**Comment by palanglois** [comment]
Hello!

Thanks for your interest in this project!

Yes, the algorithm's complexity is roughly cubic w.r.t the number of planes you insert in the plane arrangement. However, I noticed that most of the time, a number of 100 to 150 planes is sufficient for the scenes I've tried to reconstruct. 

My advice:

Try to restrict the number of planes that are being inserted: you can use the `line_based_recons_param -np 120 ...` for instance.

Also, I guess you're trying the method on a new scene, if so be sure to follow the instructions located [here](https://github.com/palanglois/line-surface-reconstruction/tree/master/full_examples/from_raw_images).

I hope this helps!
Pierre-Alain
