### ISSUE TITLE
how to download the dataset meetingroom

### ISSUE THREAD

**Issue by qco-11** [palanglois/line-surface-reconstruction#5]
Dear  Palanglois, Thank you for share such a nice code in advance, and it's working well in my computer.
Recently，I read Supplementary Material of the paper, I am interested in the dataset meetingroom of the paper, but I don't know how to download it, can you provide it to me?

**Comment by palanglois** [comment]
Dear qco,

Thank you for your interest in the project.
You can download the raw images [here](https://drive.google.com/file/d/1ZX-FR792D2zpRPGNHZAfaqxxwQGpQN1M/view?usp=sharing).

Best regards,
Pierre-Alain

**Comment by qco-11** [comment]
Thanks for your help， I download  it successfully.
